service: result

# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    REGION: us-east-1
    STAGE: dev
  region: ${self:provider.environment.REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: arn:aws:lambda:*:*:function:totals-${opt:stage, self:provider.stage}-increment
    - Effect: Allow
      Action:
        - sqs:DeleteMessage
        - sqs:SendMessage
        - sqs:GetQueueUrl
      Resource: arn:aws:sqs:*:*:totals-${opt:stage, self:provider.stage}-increment

functions:
  create:
    handler: handler.create
    name: ${self:service}-${opt:stage, self:provider.stage}-create
    events:
      - http:
          path: result/create
          method: post
          cors: true
  update:
    handler: handler.update
    name: ${self:service}-${opt:stage, self:provider.stage}-update
    events:
      - http:
          path: result/update/{id}
          method: put
          cors: true
  get:
    handler: handler.get
    name: ${self:service}-${opt:stage, self:provider.stage}-get
    events:
      - http:
          path: result/{id}
          method: get
          cors: true

resources:
  Resources:
    ResultDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        